/* eslint-disable camelcase */
/* eslint-disable no-undef */
var module = {
  shops: [name, user_id, managerFiles_id, description, url, template, status],
  categories: [category_lang, product_id, parent, ancestors, managerFiles_id, status, shop_id],
  'categories_langs_id(e)': [
    name,
    lang_id,
    description,
    linkRewrite,
    metaTitle,
    metaKeywords,
    metaDescription,
    shop_id
  ],
  managerFiles: [fieldname, originalname, encoding, mimetype, destination, filename, path, size, shop_id],
  langs: [name, managerFiles_id, isoCode, languageCode, locale, dateFormatLite, dateFormatFull, status, shop_id],
  manager_file_types: [name, width, height, containerModules, shop_id],
  alias: [nameLang, systemName, status],
  dataTypes: [nameLang, alias_id, system, status, shop_id],
  thirds: [name, typeThird_id, typeDocument_id, numberDocument, phone, email, address, status, shop_id],
  taxes: [value, status, taxLangs, shop_id],
  features: [nameLang, typeFeature_id, status, shop_id],
  feature_details: [feature_id, nameLang, status, shop_id],
  movements: [
    product_id,
    featureDetails_id,
    typeMovement_id,
    quantity,
    balance,
    cost,
    price,
    order_id,
    shop_id,
    status
  ],
  shippers: [
    third_id,
    url,
    shippingSpeed,
    shippingCost,
    maxWidth,
    maxHeight,
    maxDepth,
    maxWeight,
    rate,
    isFree,
    status,
    managerFile_id,
    shop_id
  ],
  groups: [percentDiscount, productsGroups_id, shop_id],
  orders: [
    order_code,
    productos_id,
    pay_type,
    shipper_id,
    tracking_code,
    invoice_number,
    message,
    total,
    shop_id,
    status,
    user_id
  ],
  users: ['address_id(e)', shop_id],
  crafts: [name, products_id, description, urlVideo, shop_id],
  products: [
    category_id,
    productLangs,
    managerFiles_id,
    tax_id,
    maker_id,
    provider_id,
    barCode,
    code,
    quantity,
    quantityMin,
    cost,
    price,
    profit,
    percentDiscount,
    shippingData,
    showPrice,
    onlineOnly,
    isOffer,
    availableNow,
    deliveryInStock,
    outstanding,
    status,
    shop_id
  ],
  'productLangs_id(e)': [
    lang_id,
    description,
    descriptionShort,
    linkRewrite,
    metaDescription,
    metaKeywords,
    metaTitle,
    name,
    availableLater,
    deliveryOutStock
  ],
  'shippingData_id(e)': [shipper_id, location, width, height, depth, weight]
};
